config/routes.rb
Rails.application.routes.draw do
  resources :recovereds

  resources :bills

  resources :banks
 
  resources :rules

  resources :loans

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  devise_for :users
  get 'pages/page'
 

  resources :loanrecoveries do
  collection { post :import }
end

   root 'loanrecoveries#index'

end

app/models/loanrecovery.rb
require 'roo'
class Loanrecovery < ActiveRecord::Base
  belongs_to :bank 
  has_many :bill
  has_one :recovered
  belongs_to :loan
  validates_format_of :email, :with =>/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i   
  validates :name,:phone,:address,:status,:bankname,:loanname, presence: true, allow_blank: false
	validates :phone_number, format: { with: /\d{10}/, message: "bPhone no. should contain 10 digits" }

def self.import(file)
  allowed_attributes = ["name","phone","address","email","status"]
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
  row = Hash[[header, spreadsheet.row(i)].transpose]
  product = find_by_id(row["id"]) || new
  product.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
  product.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path, packed:nil, file_warning: :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, packed:nil, file_warning: :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
end

 

app/controllers/loanrecoveries_controller.rb
class LoanrecoveriesController < ApplicationController
  before_action :set_loanrecovery, only: [:show, :edit, :update, :destroy]
  def import
  Loanrecovery.import(params[:file])
  redirect_to loanrecoveries_path, notice: "Defaulter imported."
end

  # GET /loanrecoveries
  # GET /loanrecoveries.json
  def index
   @loanrecoveries = Loanrecovery.all
   #@loanrecoveries = Loanrecovery.where("bank_id= ?", params[:banks])
   #@loanrecoveries = Loanrecovery.joins(:banks).where("banks.id = 1")


  end

  # GET /loanrecoveries/1
  # GET /loanrecoveries/1.json
  def show
  end

  # GET /loanrecoveries/new
  def new
    @loanrecovery = Loanrecovery.new

  end

  # GET /loanrecoveries/1/edit
  def edit
  end



  # POST /loanrecoveries
  # POST /loanrecoveries.json
  def create
    @loanrecovery = Loanrecovery.new(loanrecovery_params)

    respond_to do |format|
      if @loanrecovery.save
        format.html { redirect_to @loanrecovery, notice: 'Defaulter was successfully created.' }
        format.json { render :show, status: :created, location: @loanrecovery }
      else
        format.html { render :new }
        format.json { render json: @loanrecovery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loanrecoveries/1
  # PATCH/PUT /loanrecoveries/1.json
  def update
    respond_to do |format|
      if @loanrecovery.update(loanrecovery_params) 
        format.html { redirect_to @loanrecovery, notice: 'Defaulter was successfully updated.' }
        format.json { render :show, status: :ok, location: @loanrecovery }


      else
        format.html { render :edit }
        format.json { render json: @loanrecovery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loanrecoveries/1
  # DELETE /loanrecoveries/1.json
  def destroy
    @loanrecovery.destroy
    respond_to do |format|
      format.html { redirect_to loanrecoveries_url, notice: 'Defaulter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loanrecovery
      @loanrecovery = Loanrecovery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loanrecovery_params
      params.require(:loanrecovery).permit(:name, :phone, :address, :email, :status, :bankname,:loanname)
    end
end

app/helpers/loanrecoveries_helper.rb
module LoanrecoveriesHelper
end

app/views/loanrecoveries/_form.html.erb
<%= form_for(@loanrecovery) do |f| %>
  <% if @loanrecovery.errors.any? %>
   <div id="error_explanation">
    <h2><%= pluralize(@loanrecovery.errors.count, "error") %> prohibited this loanrecovery from being saved:</h2>
    <ul>
     <% @loanrecovery.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
    </ul>
   </div>
  <% end %>
 <%= f.fields_for :bills do |p| %>
  <table align="center">
   <tr align="right">
    <div class="field">
     <td align="right"><h4><%= f.label :name %></h4></td>
     <td align="right" style="padding-left:30px"><%= f.text_field :name, size: "70x10", class: "form-control input-lg", placeholder: "Enter Defaulter Name"%></td>
    </div>
   </tr>
   <tr><td><br></td></tr>
   <tr align="right">
    <div class="field">
     <td align="right"><label><h4><%= f.label :phone %></h4></label></td>
     <td align="right" style="padding-left:30px"><%= f.text_field :phone, size: "70x15", class: "form-control input-lg", placeholder: "Contact Number"%></td>
    </div></tr>
   <tr><td><br></td></tr>
   <tr align="right">
    <div class="field">
     <td align="right"> <h4><%= f.label :address %></h4></td>
     <td align="right" style="padding-left:30px"> <%= f.text_field :address, size: "70x15", class: "form-control input-lg", placeholder: " Defaulter Address"%></td>
    </div>
   </tr>
   <tr><td><br></td></tr>
   <tr align="right">
    <div class="field">
     <td align="right"> <h4><%= f.label :email %></h4></td>
     <td align="right" style="padding-left:30px"> <%= f.text_field :email, size: "70x15", class: "form-control input-lg", placeholder: "Emai ID"%></td>
    </div></tr>
   <tr><td><br></td></tr>
   <tr align="right">
    <div class="field">
     <td align="right"> <h4><%= f.label :status %></h4></td>
     <td align="left" style="padding-left:30px"> <%= f.radio_button :status, '1' %> 1<br /><%= f.radio_button :status, '0' %> 0<br /</td>
    </div></tr>
   <tr><td><br></td></tr>
   <tr align="right">
    <div class="field">
     <td align="right"> <h4><%= p.label :totalamount %></h4></td>
     <td align="right" style="padding-left:30px"> <%= p.text_field :totalamount, size: "70x15", class: "form-control input-lg", placeholder: "Enter Total Amount"%></td>
    </div>
   </tr>
   <tr><td><br></td></tr>
   <tr align="right">
    <div class="field">
     <td align="right"> <h4><%= p.label :amount_paid %></h4></td>
     <td align="right" style="padding-left:30px"> <%= p.text_field :amount_paid, size: "70x15", class: "form-control input-lg", placeholder: "Enter The Paid Amount"%></td>
    </div>
   </tr>
   <tr><td><br></td></tr>
   <tr align="right">
    <div class="field">
     <td align="right"> <h4><%= p.label :remained_amount %></h4></td>
     <td align="right" style="padding-left:30px"> <%= p.text_field :remained_amount, size: "70x15", class: "form-control input-lg", placeholder: "Enter The Remained Amount"%></td>
    </div>
   </tr>
   <tr><td><br></td></tr>
   <tr align="right">
    <div class="field">
     <td align="right"> <h4><%= p.label :dateofpayment %></h4></td>
     <td align="left" style="padding-left:30px"> <%= p.text_field :dateofpayment,id:"datepicker"%></td>
    </div>
   </tr>
  </table>
  <br><br>
  <div class="actions" align="center">
   <input class="btn btn-inverse my-btn" type="submit" value="Update Defaulter"></input>
  </div>
 <% end %>
<% end %>

app/views/loanrecoveries/edit.html.erb
<h1 align="center">Updating Defaulter</h1>
<hr></hr>
<%= render 'form' %>
<ul class="pager">
	<li><%= link_to 'Back', loanrecoveries_path %></li>
</ul>

app/views/loanrecoveries/index.html.erb
<div class="mt">
<table width="100%">
<tr>
 <td><h1>Defaulters Information</h1></td>
<!--<td align="right"><label>Import Defaulters List</label></td>

<td align="left"><%= form_tag import_loanrecoveries_path, multipart: true do %>
  <%= file_field_tag :file %></td>
  <td align="right"><%= submit_tag "Import" %>
<% end %></td> -->

<td align="right"><label class="btn btn-inverse btn-file my-btn"><div><input name="utf8" class="my-btn" type="hidden" value="&#x2713;" /><input name="authenticity_token" class="mybtn" type="hidden" value="AX0Jj45X2Ob6LvVvq+fUpm12c+f/2B3hT/B6pqK0LWA=" /></div><span class="glyphicon glyphicon-folder-open"></span>&nbsp&nbsp<label class="my-btn"><a href="#" class="popup-link-1"><label class="my-btn">Import Defaulters List</label></a></label></label>

<a href="/loanrecoveries/new" class="btn btn-inverse my-btn" role="button"><i class="fa fa-plus fa-lg my-btn"></i>&nbsp&nbsp<label class="my-btn">Create Defaulter</label></a></td></tr></table>

<table id="loan_table" class="display responsive no-wrap">
 
  <thead>
    <tr>
   
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Email</th>
      <th>Status</th>
      <th>Bank</th>
      <th>Loan</th>
            <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
  <% @loanrecoveries=Loanrecovery.all %>

    <% @loanrecoveries.each do |loanrecovery| %>

   
      <tr>
    
        <td  data-link="<%= edit_loanrecovery_path(loanrecovery) %>", style="cursor:pointer" ><%= loanrecovery.name %></a></td>
        <td data-link="<%= edit_loanrecovery_path(loanrecovery) %>", style="cursor:pointer" ><%= loanrecovery.phone %></td>
        <td data-link="<%= edit_loanrecovery_path(loanrecovery) %>", style="cursor:pointer" ><%= loanrecovery.address %></td>
        <td data-link="<%= edit_loanrecovery_path(loanrecovery) %>", style="cursor:pointer" ><%= loanrecovery.email %></td>
        <td data-link="<%= edit_loanrecovery_path(loanrecovery) %>", style="cursor:pointer" ><%= loanrecovery.status %></td>
         <td data-link="<%= edit_loanrecovery_path(loanrecovery) %>", style="cursor:pointer" ><%= loanrecovery.bankname%></td>
         <td data-link="<%= edit_loanrecovery_path(loanrecovery) %>", style="cursor:pointer" ><%= loanrecovery.loanname%></td>
      <!--  <td><%= link_to 'Show', loanrecovery %></td>
        <td><%= link_to 'Edit', edit_loanrecovery_path(loanrecovery) %></td> -->
        <td><%= link_to 'Destroy', loanrecovery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
</div>

<div class="popup-box" id="popup-box-1">
    <div class="close">X</div>
    <div class="top">
        <h2>Import File....</h2>
    </div>
    <div class="bottom">
        


<%= form_tag import_loanrecoveries_path, class: 'btn btn-inverse', multipart: true do %>
  <%= file_field_tag :file %>
  <div align="center">
  <button type="submit" class="btn btn-inverse">Import</button></div>
<% end %>


    </div>
</div>

app/views/loanrecoveries/new.html.erb
<%= form_for(@loanrecovery) do |f| %>
 <% if @loanrecovery.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@loanrecovery.errors.count, "error") %> prohibited this loanrecovery from being saved:</h2>
   <ul>
    <% @loanrecovery.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
   </ul>
  </div>
 <% end %>
 <h1 align="center">New Defaulter</h1>
 <hr></hr>
 <table align="center">
  <tr align="right">
   <div class="field">
    <td align="right"><h4><%= f.label :name %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :name, size: "70x10", class: "form-control input-lg", placeholder: "Enter Defaulter Name"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"><label><h4><%= f.label :phone %></h4></label></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :phone, size: "70x15", class: "form-control input-lg", placeholder: "Contact Number"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"> <h4><%= f.label :address %></h4></td>
    <td align="right" style="padding-left:30px"> <%= f.text_field :address, size: "70x15", class: "form-control input-lg", placeholder: " Defaulter Address"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"> <h4><%= f.label :email %></h4></td>
    <td align="right" style="padding-left:30px"> <%= f.text_field :email, size: "70x15", class: "form-control input-lg", placeholder: "Email ID"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"> <h4><%= f.label :status %></h4></td>
    <td align="right" style="padding-left:30px"> <%= f.text_field :status, size: "70x15", class: "form-control input-lg", placeholder: "Status", width: "500px" %></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field" >	
    <td align="right"><h4><%= f.label :bankname %></h4></td>
    <td align="left" style="padding-left:30px"><%= f.select:bankname,Bank.all.collect { |p| ["#{p.name},#{p.branch}"] }, {:include_blank => 'None' }, class: "form-control input-lg" %>
    </td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field" >
   <td align="right"><h4><%= f.label :loan %></h4></td>
   <td align="left" style="padding-left:30px"><%= f.select:loanname,Loan.all.collect { |p| ["#{p.loanname}"] }, {:include_blank => 'None' } , class: "form-control input-lg" %></td>
   </div>
  </tr>
 </table>
 <br><br>
 <div class="actions" align="center">
  <input class="btn btn-inverser my-btn" type="submit" value="Create Defaulter"></input>
 </div>
<% end %>
<ul class="pager">
 <li><%= link_to 'Back', loanrecoveries_path %></li>
</ul>

app/views/loanrecoveries/show.html.erb
<h1 align="center">Defaulter Information</h1>
<hr></hr>
<div class="well">
 <p>
  <strong>Name:</strong>
  <%= @loanrecovery.name %>
 </p>
 <p>
  <strong>Phone:</strong>
  <%= @loanrecovery.phone %>
 </p>
 <p>
  <strong>Address:</strong>
  <%= @loanrecovery.address %>
 </p>
 <p>
  <strong>Email:</strong>
  <%= @loanrecovery.email %>
 </p>
 <p>
  <strong>Status:</strong>
  <%= @loanrecovery.status %>
 </p>
 <ul class="pager">
  <li><%= link_to 'Edit', edit_loanrecovery_path(@loanrecovery) %> </li>
  <li><%= link_to 'Back', loanrecoveries_path %></li>
 </ul>
</div>