config/routes.rb
Rails.application.routes.draw do
  resources :recovereds

  resources :bills

  resources :banks
 
  resources :rules

  resources :loans

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  devise_for :users
  get 'pages/page'
 

  resources :loanrecoveries do
  collection { post :import }
end

   root 'loanrecoveries#index'

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	  has_many :loanrecovery
	  has_many :loan
	  belongs_to :rule
end

app/models/bill.rb
class Bill < ActiveRecord::Base
belongs_to :loanrecovery
validates :amount_paid,:remained_amount, presence: true, allow_blank: false
end

app/models/loan.rb
class Loan < ActiveRecord::Base
belongs_to :bank
belongs_to :rule
has_many :loanrecovery
end

app/models/loanrecovery.rb
require 'roo'
class Loanrecovery < ActiveRecord::Base
  belongs_to :bank 
  has_many :bill
  has_one :recovered
  belongs_to :loan
  validates_format_of :email, :with =>/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i   
  validates :name,:phone,:address,:status,:bankname,:loanname, presence: true, allow_blank: false
	validates :phone_number, format: { with: /\d{10}/, message: "bPhone no. should contain 10 digits" }

def self.import(file)
  allowed_attributes = ["name","phone","address","email","status"]
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
  row = Hash[[header, spreadsheet.row(i)].transpose]
  product = find_by_id(row["id"]) || new
  product.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
  product.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path, packed:nil, file_warning: :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, packed:nil, file_warning: :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
end

 

app/models/recovered.rb
class Recovered < ActiveRecord::Base
belongs_to :loanrecovery
end

app/models/resume.rb
class Resume < ActiveRecord::Base
end

app/models/rule.rb
class Rule < ActiveRecord::Base
has_one :loan
has_many :bank
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  after_filter :store_location

def store_location
  # store last url - this is needed for post-login redirect to whatever the user last visited.
  return unless request.get? 
  if (request.path != "/users/sign_in" &&
      request.path != "/users/sign_up" &&
      request.path != "/users/password/new" &&
      request.path != "/users/password/edit" &&
      request.path != "/users/confirmation" &&
      request.path != "/users/sign_out" &&
      !request.xhr?) # don't store ajax calls
    session[:previous_url] = request.fullpath 
  end
end

def after_sign_in_path_for(resource)
  session[:previous_url] || '/loanrecoveries'
end

def after_sign_out_path_for(resource)
  session[:previous_url] || '/users/sign_in'
end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @banks = Bank.all
    respond_with(@banks)
  end

  def show
    respond_with(@bank)
  end

  def new
    @bank = Bank.new
    respond_with(@bank)
  end

  def edit
  end

  def create
    @bank = Bank.new(bank_params)
    @bank.save
    respond_with(@bank)
  end

  def update
    @bank.update(bank_params)
    respond_with(@bank)
  end

  def destroy
    @bank.destroy
    respond_with(@bank)
  end

  private
    def set_bank
      @bank = Bank.find(params[:id])
    end

    def bank_params
      params.require(:bank).permit(:name, :address, :contact_number, :branch, :email)
    end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bills = Bill.all
    respond_with(@bills)
  end

  def show
    respond_with(@bill)
  end

  def new
    @bill = Bill.new
    respond_with(@bill)
  end

  def edit
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.save
    respond_with(@bill)
  end

  def update
    @bill.update(bill_params)
    respond_with(@bill)
  end

  def destroy
    @bill.destroy
    respond_with(@bill)
  end

  private
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.require(:bill).permit(:bill_id, :amount_paid, :remained_amount, :remained_time)
    end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @loans = Loan.all
    respond_with(@loans)
  end

  def show
    respond_with(@loan)
  end

  def new
    @loan = Loan.new
    respond_with(@loan)
  end

  def edit
  end

  def create
    @loan = Loan.new(loan_params)
    @loan.save
    #redirect_to action: "index"
    respond_with(@loan)
  end

  def update
    @loan.update(loan_params)
    respond_with(@loan)
  end

  def destroy
    @loan.destroy
    respond_with(@loan)
  end

  private
    def set_loan
      @loan = Loan.find(params[:id])
    end

    def loan_params
      params.require(:loan).permit(:loan_id, :loan_amount, :amount_paid, :loan_type, :interest_rate, :loanname,:bankname)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def page
  end
end

app/controllers/recovereds_controller.rb
class RecoveredsController < ApplicationController
  before_action :set_recovered, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @recovereds = Recovered.all
    respond_with(@recovereds)
  end

  def show
    respond_with(@recovered)
  end

  def new
    @recovered = Recovered.new
    respond_with(@recovered)
  end

  def edit
  end

  def create
    @recovered = Recovered.new(recovered_params)
    @recovered.save
    respond_with(@recovered)
  end

  def update
    @recovered.update(recovered_params)
    respond_with(@recovered)
  end

  def destroy
    @recovered.destroy
    respond_with(@recovered)
  end

  private
    def set_recovered
      @recovered = Recovered.find(params[:id])
    end

    def recovered_params
      params.require(:recovered).permit(:recovered_amount, :recovery_time, :recovery_charges)
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @rules = Rule.all
    respond_with(@rules)
  end

  def show
    respond_with(@rule)
  end

  def new
    @rule = Rule.new
    respond_with(@rule)
  end

  def edit
  end

  def create
    @rule = Rule.new(rule_params)
    @rule.save
    respond_with(@rule)
  end

  def update
    @rule.update(rule_params)
    respond_with(@rule)
  end

  def destroy
    @rule.destroy
    respond_with(@rule)
  end

  private
    def set_rule
      @rule = Rule.find(params[:id])
    end

    def rule_params
      params.require(:rule).permit(:rule_id, :rule_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
  Bank.all.collect { |m| [m.name, m.id] }
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/loanrecoveries_helper.rb
module LoanrecoveriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recovereds_helper.rb
module RecoveredsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
	<% if @bank.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>
	      <ul>
		      <% @bank.errors.full_messages.each do |message| %>
		      <li><%= message %></li>
		      <% end %>
	      </ul>
	    </div>
	<% end %>
  	<table align="center">
  		<tr align="right">
			<div class="field">
				<td align="right"><h4><%= f.label :name %></h4></td>
			  	<td align="right" style="padding-left:30px"><%= f.text_field :name, size: "70x10", class: "form-control input-lg"%></td>
			</div>
	  	</tr>
	  	<tr><td><br></td></tr>
	  	<tr align="right">
	  		<div class="field">
	    		<td align="right"><h4><%= f.label :address %></h4></td>
	    		<td align="right" style="padding-left:30px"><%= f.text_field :address, size: "70x10", class: "form-control input-lg"%></td>
	  		</div>
	  	</tr>
	  	<tr><td><br></td></tr>
	  	<tr align="right">
	  		<div class="field">
	   	 	<td align="right"><h4><%= f.label :contact_number %></h4></td>
	    	<td align="right" style="padding-left:30px"><%= f.text_field :contact_number, size: "70x10", class: "form-control input-lg"%></td>
	  		</div>
	  	</tr>
	  	<tr><td><br></td></tr>
	  	<tr align="right">
	  		<div class="field">
	    	<td align="right"><h4><%= f.label :branch %></h4></td>
	    	<td align="right" style="padding-left:30px"><%= f.text_field :branch, size: "70x10", class: "form-control input-lg"%></td>
	  		</div>
	  	</tr>
	  	<tr><td><br></td></tr>
	  	<tr align="right">
	  		<div class="field">
	    	<td align="right"><h4><%= f.label :email %></h4></td>
	    	<td align="right" style="padding-left:30px"><%= f.text_field :email, size: "70x10", class: "form-control input-lg"%></td>
	  		</div>
	  	</tr>
	  	<tr><td><br></td></tr>
	</table>
	<br><br>
	<div class="actions" align="center">
    <input class="btn btn-inverse my-btn" type="submit" value="Update Bank"></input>
  	</div>
<% end %>

app/views/banks/edit.html.erb
<h1 align="center">Editing bank</h1>
<hr></hr>
<%= render 'form' %>
<ul class="pager">
	<!--<li><%= link_to 'Show', @bank %></li>-->
	<li><%= link_to 'Back', banks_path %></li>
</ul>

app/views/banks/index.html.erb
<table width="100%">
 <tr>
  <td><h1>Banks Information</h1></td>
  <td align="right"><a href="/banks/new" class="btn btn-inverse my-btn" role="button"><i class="fa fa-plus fa-lg my-btn"></i>&nbsp&nbsp<label class="my-btn">Create Bank</label></a></td>
 </tr>
</table>

<table id="loan_table" class="display responsive no-wrap">
 <thead>
   <tr>
    <th>Bank ID</th>
      <th>Bank Name</th>
      <th>Address</th>
      <th>Contact number</th>
      <th>Branch</th>
      <th>Email</th>
      <th>Rule</th>
      <!--<th>Show</th>
	     <th>Edit</th> -->
      <th>Destroy</th>
    </tr>
 </thead>
 <tbody>
  <% @banks=Bank.all %>
   <% @banks.each do |bank| %>
    <tr>
     <td  data-link="<%= edit_bank_path(bank) %>", style="cursor:pointer" ><%= bank.id %></td>
     <td  data-link="<%= edit_bank_path(bank) %>", style="cursor:pointer" ><%= bank.name %></td>
     <td  data-link="<%= edit_bank_path(bank) %>", style="cursor:pointer" ><%= bank.address %></td>
     <td  data-link="<%= edit_bank_path(bank) %>", style="cursor:pointer" ><%= bank.contact_number %></td>
     <td  data-link="<%= edit_bank_path(bank) %>", style="cursor:pointer" ><%= bank.branch %></td>
     <td  data-link="<%= edit_bank_path(bank) %>", style="cursor:pointer" ><%= bank.email %></td>
     <td  data-link="<%= edit_bank_path(bank) %>", style="cursor:pointer" ><%= bank.rule.rule_name if bank.rule %></td>      
     <!-- <td><%= link_to 'Show', bank %></td>
     <td><%= link_to 'Edit', edit_bank_path(bank) %></td> -->
     <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
   <% end %>
 </tbody>
</table>

app/views/banks/new.html.erb
<h1 align="center">New Bank</h1>
<hr></hr>
<%= form_for(@bank) do |f| %>
 <% if @bank.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this rule from being saved:</h2>
   <ul>
    <% @bank.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
   </ul>
  </div>
 <% end %>
 <table align="center">
  <tr align="right">
   <div class="field">
    <td align="right"><h4><%= f.label :name %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :name, size: "70x10", class: "form-control input-lg", placeholder: "Enter Bank Name"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"><h4><%= f.label :address %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :address, size: "70x10", class: "form-control input-lg", placeholder: "Enter Bank Address"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"><h4><%= f.label :contact_number %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :contact_number, size: "70x10", class: "form-control input-lg", placeholder: "Enter Bank Contact no."%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"><h4><%= f.label :branch %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :branch, size: "70x10", class: "form-control input-lg", placeholder: "Enter Bank Branch"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"><h4><%= f.label :email %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :email, size: "70x10", class: "form-control input-lg", placeholder: "Enter Bank Email-id"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
 </table>
 <div class="actions" align="center">
  <input class="btn btn-inverser my-btn" type="submit" value="Create Bank"></input>
 </div>
<% end %>
<ul class="pager">
 <li><%= link_to 'Back', rules_path %></li>
</ul>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bank.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @bank.address %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @bank.contact_number %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @bank.branch %>
</p>

<p>
  <strong>Email:</strong>
  <%= @bank.email %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
 <% if @bill.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>
   <ul>
    <% @bill.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
   </ul>
  </div>
 <% end %>

 <table align="center">
  <tr align="right">
   <div class="field">
    <td align="right"><h4> <%= f.label :bill_id %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :bill_id, size: "70x10", class: "form-control input-lg", placeholder: "Enter Bill ID"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"><label><h4><%= f.label :amount_paid %></h4></label></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :amount_paid, size: "70x15", class: "form-control input-lg", placeholder: "Enter Amount Paid"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"> <h4><%= f.label :remained_amount %></h4></td>
    <td align="right" style="padding-left:30px"> <%= f.text_field :remained_amount, size: "70x15", class: "form-control input-lg", placeholder: "Amount To Be Paid"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
 </table>
 <div class="actions" align="center">
  <input class="btn btn-inverse my-btn" type="submit" value="New Bill"></input>
 </div>
<% end %>

app/views/bills/edit.html.erb
<%= form_for(@bill) do |f| %>
 <% if @bill.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>
   <ul>
    <% @bill.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
   </ul>
  </div>
 <% end %>
 <h1 align="center">Editing bill</h1>
 <hr></hr>
 <%= f.fields_for :loanrecoveries do |p| %>
  <table class="tab" align="center">
   <tr>
    <td><%= p.label :name %></td>
    <td><%= p.text_field :name %></td>
   </tr>
   <tr>
    <td>Account No:</td>
    <td></td>
   </tr>
   <tr>
    <td>Contact Number:</td>
    <td></td>
   </tr>
   <hr></hr>
   <tr>
    <div class="field">
     <td><%= f.label :bill_id %></td>
     <td> <%= f.number_field :bill_id %></td>
    </div>
   </tr>
   <tr>
    <div class="field">
     <td><%= f.label :amount_paid %></td>
     <td><%= f.number_field :amount_paid %></td>
    </div>
   </tr>
   <tr>
    <div class="field">
     <td><%= f.label :remained_amount %></td>
     <td><%= f.number_field :remained_amount %></td>
    </div>
   </tr>
   <tr>
    <div class="field">
     <td><%= f.label :remained_time %></td>
     <td><%= f.number_field :remained_time %></td>
    </div>
   </tr>
   <tr>
    <div class="actions">
     <td align="center"><button type="submit" class="btn btn-inverse my-btn">Save Bill</button><button type="botton" class="btn btn-inverse my-btn">Print Bill</button></td>
    </div>
   </tr>
  <%end%>
 </table>
<% end %>
<ul class="pager">
 <li><%= link_to 'Show', @bill %> </li>
 <li><%= link_to 'Back', bills_path %></li>
</ul>

app/views/bills/index.html.erb
<table width="100%">
<tr>
<td><h1>Bill Information</h1></td>
<td align="right">
<a href="/bills/new" class="btn btn-inverse my-btn" role="button"><i class="fa fa-plus fa-lg my-btn"></i>&nbsp&nbsp<label class="my-btn">Create Bill</label></a>
</td></tr></table>
<table id="loan_table" class="display responsive no-wrap">
  <thead>
    <tr>
      <th>Bill ID</th>
      <th>Amount paid</th>
      <th>Remained amount</th>
      <th>Remained time</th>
<th>Defaulter Name</th>

<th>Destroy</th>
    </tr>
  </thead>

  <tbody>
  <% @bills=Bill.all %>

    <% @bills.each do |bill| %>
      <tr>
        <td  data-link="<%= edit_bill_path(bill) %>", style="cursor:pointer" ><%= bill.id %></td>
        <td  data-link="<%= edit_bill_path(bill) %>", style="cursor:pointer" ><%= bill.amount_paid %></td>
        <td  data-link="<%= edit_bill_path(bill) %>", style="cursor:pointer" ><%= bill.remained_amount %></td>
       <td  data-link="<%= edit_bill_path(bill) %>", style="cursor:pointer" ><%= bill.remained_time %></td>
	<td  data-link="<%= edit_bill_path(bill) %>", style="cursor:pointer" ><%= bill.loanrecovery.name if bill.loanrecovery %>
      
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bills/new.html.erb
<h1 align="center">New bill</h1>
<%= render 'form' %>
<ul class="pager">
	<li><%= link_to 'Back', bills_path %></li>
</ul>

app/views/bills/show.html.erb
<h1 align="center">Billing Information</h1>
<hr></hr>
<div class="well">
	<p id="notice"><%= notice %></p>
	<p>
	  <strong>Bill:</strong>
	  <%= @bill.bill_id %>
	</p>

	<p>
	  <strong>Amount paid:</strong>
	  <%= @bill.amount_paid %>
	</p>

	<p>
	  <strong>Remained amount:</strong>
	  <%= @bill.remained_amount %>
	</p>

	<p>
	  <strong>Remained time:</strong>
	  <%= @bill.remained_time %>
	</p>

	<ul class="pager">
		<li><%= link_to 'Edit', edit_bill_path(@bill) %> </li>
		<li><%= link_to 'Back', bills_path %></li>
	</ul>
</div>

app/views/recovereds/_form.html.erb
<%= form_for(@recovered) do |f| %>
 <% if @recovered.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@recovered.errors.count, "error") %> prohibited this recovered from being saved:</h2>
   <ul>
    <% @recovered.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
   </ul>
  </div>
 <% end %>

 <table align="center">
  <tr align="right">
   <div class="field">
    <td align="right"><h4>
    <%= f.label :recovered_amount %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.number_field :recovered_amount, class: "form-control input-lg", placeholder: "Enter Recovered Amount" %></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"><h4>
    <%= f.label :recovery_time %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.number_field :recovery_time, class: "form-control input-lg", placeholder: "Enter Recovery Time" %></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"><h4>
    <%= f.label :recovery_charges %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.number_field :recovery_charges, class: "form-control input-lg", placeholder: "Enter Recovery Charges" %></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
 </table>
 <div class="actions" align="center">
  <input class="btn btn-inverse my-btn" type="submit" value="Update Recovery"></input>
 </div>
<% end %>

app/views/recovereds/edit.html.erb
<h1 align="center">Editing recovered</h1>
<%= render 'form' %>
<ul class="pager">
	<li><%= link_to 'Back', recovereds_path %></li>
</ul>

app/views/recovereds/index.html.erb
<table width="100%">
<tr>
<td align="left"><h1>Recovered Defaulters</h1></td>
<td align="right"><a href="/recovereds/new" class="btn btn-inverse my-btn" role="button"><i class="fa fa-plus fa-lg my-btn"></i>&nbsp&nbsp<label class="my-btn">Create Recovery</label></td>
</tr></table>


<table id="loan_table" class="display responsive no-wrap">
  <thead>
    <tr>
	<th>Defaulter Name</th>
      <th>Recovered amount</th>
      <th>Recovery time</th>
      <th>Recovery charges</th>
     <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
  <% @recovereds=Recovered.all %>

    <% @recovereds.each do |recovered| %>
      <tr>
	<td  data-link="<%= edit_recovered_path(recovered) %>", style="cursor:pointer" ><%= recovered.loanrecovery.name if recovered.loanrecovery %></td>
        <td  data-link="<%= edit_recovered_path(recovered) %>", style="cursor:pointer" ><%= recovered.recovered_amount %></td>
        <td  data-link="<%= edit_recovered_path(recovered) %>", style="cursor:pointer" ><%= recovered.recovery_time %></td>
        <td  data-link="<%= edit_recovered_path(recovered) %>", style="cursor:pointer" ><%= recovered.recovery_charges %></td>
       
        <td><%= link_to 'Destroy', recovered, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/recovereds/new.html.erb
<h1>New recovered</h1>

<%= form_for(@recovered) do |f| %>
  <% if @recovered.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recovered.errors.count, "error") %> prohibited this recovered from being saved:</h2>

      <ul>
      <% @recovered.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table align="center"><tr align="right">
  <div class="field">
    <td align="right"><h4>
    <%= f.label :recovered_amount %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.number_field :recovered_amount, size: "70x10", class: "form-control input-lg", placeholder: "Enter Recovered Amount" %></td>
  </div>
</tr>
<tr><td><br></td></tr>
  <tr align="right">
  <div class="field">
    <td align="right"><h4>
    <%= f.label :recovery_time %></h4></td>
   <td align="right" style="padding-left:30px"> <%= f.number_field :recovery_time, size: "70x10", class: "form-control input-lg", placeholder: "Enter Recovered Amount" %></td>
  </div>
</tr>

<tr><td><br></td></tr>
  <tr align="right">
  <div class="field">
    <td align="right"><h4>
    <%= f.label :recovery_charges %></h4></td>
    <td align="right" style="padding-left:30px"> <%= f.number_field :recovery_charges, size: "70x10", class: "form-control input-lg", placeholder: "Enter Recovered Amount" %></td>
  </div>
</tr>
<tr><td><br></td></tr>
</table>
  <div class="actions" align="center">
    <input class="btn btn-inverser my-btn" type="submit" value="Create Recovery"></input>
  </div>
<% end %>
<ul class="pager">
<li><%= link_to 'Back', recovereds_path %></li>
</ul>

app/views/recovereds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recovered amount:</strong>
  <%= @recovered.recovered_amount %>
</p>

<p>
  <strong>Recovery time:</strong>
  <%= @recovered.recovery_time %>
</p>

<p>
  <strong>Recovery charges:</strong>
  <%= @recovered.recovery_charges %>
</p>

<%= link_to 'Edit', edit_recovered_path(@recovered) %> |
<%= link_to 'Back', recovereds_path %>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<h1>Resumes#index</h1>
<p>Find me in app/views/resumes/index.html.erb</p>

app/views/resumes/new.html.erb
<h1>Resumes#new</h1>
<p>Find me in app/views/resumes/new.html.erb</p>