config/routes.rb
Rails.application.routes.draw do
  resources :recovereds

  resources :bills

  resources :banks
 
  resources :rules

  resources :loans

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  devise_for :users
  get 'pages/page'
 

  resources :loanrecoveries do
  collection { post :import }
end

   root 'loanrecoveries#index'

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	  has_many :loanrecovery
	  has_many :loan
	  belongs_to :rule
end

app/models/bill.rb
class Bill < ActiveRecord::Base
belongs_to :loanrecovery
validates :amount_paid,:remained_amount, presence: true, allow_blank: false
end

app/models/loan.rb
class Loan < ActiveRecord::Base
belongs_to :bank
belongs_to :rule
has_many :loanrecovery
end

app/models/loanrecovery.rb
require 'roo'
class Loanrecovery < ActiveRecord::Base
  belongs_to :bank 
  has_many :bill
  has_one :recovered
  belongs_to :loan
  validates_format_of :email, :with =>/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i   
  validates :name,:phone,:address,:status,:bankname,:loanname, presence: true, allow_blank: false
	validates :phone_number, format: { with: /\d{10}/, message: "bPhone no. should contain 10 digits" }

def self.import(file)
  allowed_attributes = ["name","phone","address","email","status"]
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
  row = Hash[[header, spreadsheet.row(i)].transpose]
  product = find_by_id(row["id"]) || new
  product.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
  product.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path, packed:nil, file_warning: :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, packed:nil, file_warning: :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
end

 

app/models/recovered.rb
class Recovered < ActiveRecord::Base
belongs_to :loanrecovery
end

app/models/resume.rb
class Resume < ActiveRecord::Base
end

app/models/rule.rb
class Rule < ActiveRecord::Base
has_one :loan
has_many :bank
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @banks = Bank.all
    respond_with(@banks)
  end

  def show
    respond_with(@bank)
  end

  def new
    @bank = Bank.new
    respond_with(@bank)
  end

  def edit
  end

  def create
    @bank = Bank.new(bank_params)
    @bank.save
    respond_with(@bank)
  end

  def update
    @bank.update(bank_params)
    respond_with(@bank)
  end

  def destroy
    @bank.destroy
    respond_with(@bank)
  end

  private
    def set_bank
      @bank = Bank.find(params[:id])
    end

    def bank_params
      params.require(:bank).permit(:name, :address, :contact_number, :branch, :email)
    end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bills = Bill.all
    respond_with(@bills)
  end

  def show
    respond_with(@bill)
  end

  def new
    @bill = Bill.new
    respond_with(@bill)
  end

  def edit
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.save
    respond_with(@bill)
  end

  def update
    @bill.update(bill_params)
    respond_with(@bill)
  end

  def destroy
    @bill.destroy
    respond_with(@bill)
  end

  private
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.require(:bill).permit(:bill_id, :amount_paid, :remained_amount, :remained_time)
    end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @loans = Loan.all
    respond_with(@loans)
  end

  def show
    respond_with(@loan)
  end

  def new
    @loan = Loan.new
    respond_with(@loan)
  end

  def edit
  end

  def create
    @loan = Loan.new(loan_params)
    @loan.save
    #redirect_to action: "index"
    respond_with(@loan)
  end

  def update
    @loan.update(loan_params)
    respond_with(@loan)
  end

  def destroy
    @loan.destroy
    respond_with(@loan)
  end

  private
    def set_loan
      @loan = Loan.find(params[:id])
    end

    def loan_params
      params.require(:loan).permit(:loan_id, :loan_amount, :amount_paid, :loan_type, :interest_rate, :loanname,:bankname)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def page
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @rules = Rule.all
    respond_with(@rules)
  end

  def show
    respond_with(@rule)
  end

  def new
    @rule = Rule.new
    respond_with(@rule)
  end

  def edit
  end

  def create
    @rule = Rule.new(rule_params)
    @rule.save
    respond_with(@rule)
  end

  def update
    @rule.update(rule_params)
    respond_with(@rule)
  end

  def destroy
    @rule.destroy
    respond_with(@rule)
  end

  private
    def set_rule
      @rule = Rule.find(params[:id])
    end

    def rule_params
      params.require(:rule).permit(:rule_id, :rule_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
  Bank.all.collect { |m| [m.name, m.id] }
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/loanrecoveries_helper.rb
module LoanrecoveriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recovereds_helper.rb
module RecoveredsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loan Recovery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= csrf_meta_tags %>
   <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script type="text/javascript" src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.9/js/dataTables.jqueryui.min.js"></script>
<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.9/css/dataTables.jqueryui.min.css"/>

<!-- <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
 -->

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<style type="text/css">
  
  .popup-box {
    position: absolute;
    border-radius: 5px;
    background: #fff;
    display: none;
    box-shadow: 1px 1px 5px rgba(0,0,0,0.2);
    font-family: Arial, sans-serif;
    z-index: 9999999;
    font-size: 14px;
}
 
.popup-box .close {
    position: absolute;
    top: 0px;
    right: 0px;
    font-family: Arial, Helvetica, sans-serif;  
    font-weight: bold;
    cursor: pointer;
    color: #434343;
    padding: 20px;
    font-size: 20px;
}
 
.popup-box .close:hover {
    color: #000;
}
 
.popup-box h2 {
    padding: 0;
    margin: 0;
    font-size: 18px;
}
.popup-box .top {
    padding: 20px;
}
 
.popup-box .bottom {
    background: #eee;
    border-top: 1px solid #e5e5e5;
    padding: 20px;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
}
 
#blackout {
    background: rgba(0,0,0,0.3);
    position: absolute;
    top: 0;
    overflow: hidden;
    z-index: 999999;
    left: 0;
    display: none;
}
</style>

   <script type="text/javascript"> 
      $(document).ready( function() {
        $('#deletesuccess').delay(3000).fadeOut();
      });
$(".nav a").on("click", function(){
   $(".nav").find(".active").removeClass("active");
   $(this).parent().addClass("active");
});


$(document).ready(function() {


  $('body').append('<div class="popup-box" id="popup-box-1"><div class="close">X</div><div class="top"><h2>Hi, it is demo window!</h2></div><div class="bottom">Sample content!</div></div>');
  $('body').append('<div id="blackout"></div>');
  
  var boxWidth = 400;
  
  function centerBox() {
    
    /* Preliminary information */
    var winWidth = $(window).width();
    var winHeight = $(document).height();
    var scrollPos = $(window).scrollTop();
    /* auto scroll bug */
    
    /* Calculate positions */
    
    var disWidth = (winWidth - boxWidth) / 2
    var disHeight = scrollPos + 150;
    
    /* Move stuff about */
    $('.popup-box').css({'width' : boxWidth+'px', 'left' : disWidth+'px', 'top' : disHeight+'px'});
    $('#blackout').css({'width' : winWidth+'px', 'height' : winHeight+'px'});
  
    return false;
  }
  
  
  $(window).resize(centerBox);
  $(window).scroll(centerBox);
  centerBox();  

  $('[class*=popup-link]').click(function(e) {
  
    /* Prevent default actions */
    e.preventDefault();
    e.stopPropagation();
    
    /* Get the id (the number appended to the end of the classes) */
    var name = $(this).attr('class');
    var id = name[name.length - 1];
    var scrollPos = $(window).scrollTop();
    
    /* Show the correct popup box, show the blackout and disable scrolling */
    $('#popup-box-'+id).show();
    $('#blackout').show();
    $('html,body').css('overflow', 'hidden');
    
    /* Fixes a bug in Firefox */
    $('html').scrollTop(scrollPos);
  });
  $('[class*=popup-box]').click(function(e) { 
    /* Stop the link working normally on click if it's linked to a popup */
    e.stopPropagation(); 
  });
  $('html').click(function() { 
    var scrollPos = $(window).scrollTop();
    /* Hide the popup and blackout when clicking outside the popup */
    $('[id^=popup-box-]').hide(); 
    $('#blackout').hide(); 
    $("html,body").css("overflow","auto");
    $('html').scrollTop(scrollPos);
  });
  $('.close').click(function() { 
    var scrollPos = $(window).scrollTop();
    /* Similarly, hide the popup and blackout when the user clicks close */
    $('[id^=popup-box-]').hide(); 
    $('#blackout').hide(); 
    $("html,body").css("overflow","auto");
    $('html').scrollTop(scrollPos);
  });
});
$(function() {
    		$( "#datepicker" ).datepicker();
  		});

    </script>

 
</head>
<body>
<div class="mt">
<% if notice %>
  <p class="alert alert-success" id="deletesuccess"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger" id="deletesuccess"><%= alert %></p>
<% end %>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Loan Recovery</a>
  <!--     <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> -->
    </div>
    <div>
   
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
<!--             <a class="navbar-brand" href="/loanrecoveries">Loan Recovery</a>
 -->
        <li class="<%= 'active' if params[:controller] == 'loanrecoveries' %>"><a href="/loanrecoveries">Defaulters</a></li>
	<li class="<%= 'active' if params[:controller] == 'bills' %>"><a href="/bills">Bill</a></li>
        <li class="<%= 'active' if params[:controller] == 'banks' %>"><a href="/banks">Bank</a></li>
        <li class="<%= 'active' if params[:controller] == 'loans' %>"><a href="/loans">Loan Information</a></li>
	<li class="<%= 'active' if params[:controller] == 'rules' %>"><a href="/rules">Rules</a></li>
	<li class="<%= 'active' if params[:controller] == 'recovereds' %>"><a href="/recovereds">Recovered Data</a></li>
      </ul>
   <p class="navbar-text pull-right"> 
  <strong ><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></p>
<% else %>
   <p class="navbar-text pull-right"> 
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
</p>
<% end %>
    </div>
  </div>
</nav>

<%= yield %>
</div>
</body>
</html>

app/views/pages/page.html.erb
<div class="well">
<h2>Import Defaulters List</h2>

<%= form_tag import_loanrecoveries_path, multipart: true, do %>
  <%= file_field_tag :file %><br><br>
  <div align="center">
  <button type="submit" class="btn btn-primary">Import</button></div>
<% end %>
</div>
<ul class="pager">
<li><%= link_to 'Back', loanrecoveries_path %></li>
</ul>