config/routes.rb
Rails.application.routes.draw do
  resources :recovereds

  resources :bills

  resources :banks
 
  resources :rules

  resources :loans

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  devise_for :users
  get 'pages/page'
 

  resources :loanrecoveries do
  collection { post :import }
end

   root 'loanrecoveries#index'

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	  has_many :loanrecovery
	  has_many :loan
	  belongs_to :rule
end

app/models/bill.rb
class Bill < ActiveRecord::Base
belongs_to :loanrecovery
validates :amount_paid,:remained_amount, presence: true, allow_blank: false
end

app/models/loan.rb
class Loan < ActiveRecord::Base
belongs_to :bank
belongs_to :rule
has_many :loanrecovery
end

app/models/loanrecovery.rb
require 'roo'
class Loanrecovery < ActiveRecord::Base
  belongs_to :bank 
  has_many :bill
  has_one :recovered
  belongs_to :loan
  validates_format_of :email, :with =>/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i   
  validates :name,:phone,:address,:status,:bankname,:loanname, presence: true, allow_blank: false
	validates :phone_number, format: { with: /\d{10}/, message: "bPhone no. should contain 10 digits" }

def self.import(file)
  allowed_attributes = ["name","phone","address","email","status"]
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
  row = Hash[[header, spreadsheet.row(i)].transpose]
  product = find_by_id(row["id"]) || new
  product.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
  product.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path, packed:nil, file_warning: :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, packed:nil, file_warning: :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
end

 

app/models/recovered.rb
class Recovered < ActiveRecord::Base
belongs_to :loanrecovery
end

app/models/resume.rb
class Resume < ActiveRecord::Base
end

app/models/rule.rb
class Rule < ActiveRecord::Base
has_one :loan
has_many :bank
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @banks = Bank.all
    respond_with(@banks)
  end

  def show
    respond_with(@bank)
  end

  def new
    @bank = Bank.new
    respond_with(@bank)
  end

  def edit
  end

  def create
    @bank = Bank.new(bank_params)
    @bank.save
    respond_with(@bank)
  end

  def update
    @bank.update(bank_params)
    respond_with(@bank)
  end

  def destroy
    @bank.destroy
    respond_with(@bank)
  end

  private
    def set_bank
      @bank = Bank.find(params[:id])
    end

    def bank_params
      params.require(:bank).permit(:name, :address, :contact_number, :branch, :email)
    end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bills = Bill.all
    respond_with(@bills)
  end

  def show
    respond_with(@bill)
  end

  def new
    @bill = Bill.new
    respond_with(@bill)
  end

  def edit
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.save
    respond_with(@bill)
  end

  def update
    @bill.update(bill_params)
    respond_with(@bill)
  end

  def destroy
    @bill.destroy
    respond_with(@bill)
  end

  private
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.require(:bill).permit(:bill_id, :amount_paid, :remained_amount, :remained_time)
    end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @loans = Loan.all
    respond_with(@loans)
  end

  def show
    respond_with(@loan)
  end

  def new
    @loan = Loan.new
    respond_with(@loan)
  end

  def edit
  end

  def create
    @loan = Loan.new(loan_params)
    @loan.save
    #redirect_to action: "index"
    respond_with(@loan)
  end

  def update
    @loan.update(loan_params)
    respond_with(@loan)
  end

  def destroy
    @loan.destroy
    respond_with(@loan)
  end

  private
    def set_loan
      @loan = Loan.find(params[:id])
    end

    def loan_params
      params.require(:loan).permit(:loan_id, :loan_amount, :amount_paid, :loan_type, :interest_rate, :loanname,:bankname)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def page
  end
end

app/controllers/recovereds_controller.rb
class RecoveredsController < ApplicationController
  before_action :set_recovered, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @recovereds = Recovered.all
    respond_with(@recovereds)
  end

  def show
    respond_with(@recovered)
  end

  def new
    @recovered = Recovered.new
    respond_with(@recovered)
  end

  def edit
  end

  def create
    @recovered = Recovered.new(recovered_params)
    @recovered.save
    respond_with(@recovered)
  end

  def update
    @recovered.update(recovered_params)
    respond_with(@recovered)
  end

  def destroy
    @recovered.destroy
    respond_with(@recovered)
  end

  private
    def set_recovered
      @recovered = Recovered.find(params[:id])
    end

    def recovered_params
      params.require(:recovered).permit(:recovered_amount, :recovery_time, :recovery_charges)
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @rules = Rule.all
    respond_with(@rules)
  end

  def show
    respond_with(@rule)
  end

  def new
    @rule = Rule.new
    respond_with(@rule)
  end

  def edit
  end

  def create
    @rule = Rule.new(rule_params)
    @rule.save
    respond_with(@rule)
  end

  def update
    @rule.update(rule_params)
    respond_with(@rule)
  end

  def destroy
    @rule.destroy
    respond_with(@rule)
  end

  private
    def set_rule
      @rule = Rule.find(params[:id])
    end

    def rule_params
      params.require(:rule).permit(:rule_id, :rule_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
  Bank.all.collect { |m| [m.name, m.id] }
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/loanrecoveries_helper.rb
module LoanrecoveriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recovereds_helper.rb
module RecoveredsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
 <% if @loan.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>
    <ul>
     <% @loan.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
    </ul>
  </div>
 <% end %>

 <table align="center">
  <tr align="right">
   <div class="field" >	
    <td align="right"><h4><%= f.label :bankname %></h4></td>
    <td align="left" style="padding-left:30px"><%= f.select:bankname,Bank.all.collect { |p| ["#{p.name},#{p.branch}"] }, {:include_blank => 'None' }, class: "form-control input-lg" %>
    </td>
   </div>
  </tr>
  <tr><td><br></td></tr> 
  <tr align="right">
   <div class="field">
    <td align="right"><h4><%= f.label :loanname %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :loanname, size: "70x10", class: "form-control input-lg", placeholder: "Enter Loan Name"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr> 
  <tr align="right">
   <div class="field">
    <td align="right"><label><h4> <%= f.label :loan_type %></h4></label></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :loan_type , size: "70x15", class: "form-control input-lg", placeholder: "Loan Type"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
  <tr align="right">
   <div class="field">
    <td align="right"> <h4> <%= f.label :interest_rate %></h4></td>
    <td align="right" style="padding-left:30px"> <%= f.text_field  :interest_rate, size: "70x15", class: "form-control input-lg", placeholder: " Interest Rate"%></td>
   </div>
  </tr>
  <tr><td><br></td></tr>
 </table>
 <br><br>
 <div class="actions" align="center">
  <input class="btn btn-inverse my-btn" type="submit" value="Update Loan"></input>
 </div>
<% end %>

app/views/loans/edit.html.erb
<h1 align="center">Editing loan</h1>
<hr></hr>
<%= render 'form' %>
<ul class="pager">
	<li><%= link_to 'Show', @loan %> </li>
	<li><%= link_to 'Back', loans_path %></li>
</ul>

app/views/loans/index.html.erb
<table width="100%">
<tr>
<td><h1>Loans Information!!!!!!</h1></td>
<td align="right">
<a href="/loans/new" class="btn btn-inverse my-btn" role="button"><i class="fa fa-plus fa-lg my-btn"></i>&nbsp&nbsp<label class="my-btn">Create Loan</label></a>
</td></tr></table>
<table id="loans-table" class="display">
  <thead>
    <tr>
	<th>Bank Name</th>
      <th>Loan ID</th>
	<th>Loan Name</th>
      <th>Loan type</th>
      <th>Interest rate</th>
	<th>Destroy</th>
    </tr>
  </thead>

  <tbody>
	<% @loans=Loan.all %>
    <% @loans.each do |loan| %>
      <tr>
	<td  data-link="<%= edit_loan_path(loan) %>", style="cursor:pointer" ><%= loan.bankname%></td>
        <td  data-link="<%= edit_loan_path(loan) %>", style="cursor:pointer" ><%= loan.id %></td>
	<td  data-link="<%= edit_loan_path(loan) %>", style="cursor:pointer" ><%= loan.loanname %></td>
        <td  data-link="<%= edit_loan_path(loan) %>", style="cursor:pointer" ><%= loan.loan_type %></td>
        <td  data-link="<%= edit_loan_path(loan) %>", style="cursor:pointer" ><%= loan.interest_rate %></td>
       <!-- <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>-->
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/loans/new.html.erb
<h1>New loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loan:</strong>
  <%= @loan.id%>
</p>

<p>
  <strong>Loan type:</strong>
  <%= @loan.loan_type %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @loan.interest_rate %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table align="center"><tr align="right">
  <div class="field">
    <td align="right"><h4>  
    <%= f.label :rule_id %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :rule_id, class: "form-control input-lg", placeholder: "Enter Rule ID" %></td>
  </div>
</tr>
<tr><td><br></td></tr>
  <tr align="right">
  <div class="field">
    <td align="right"><h4>
    <%= f.label :rule_name %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :rule_name, class: "form-control input-lg", placeholder: "Enter Rule Name" %></td>
  </div>
</tr>
<tr><td><br></td></tr>
</table>
  <div class="actions" align="center">
    <input class="btn btn-inverse my-btn" type="submit" value="Update Rule"></input>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1 align="center">Editing rule</h1>

<%= render 'form' %>
<ul class="pager">
<li><%= link_to 'Back', rules_path %></li>
</ul>

app/views/rules/index.html.erb
<table width="100%">
<tr>
<td align="left"><h1>Listing rules</h1></td>
<td align="right"><a href="/rules/new" class="btn btn-inverse my-btn" role="button"><i class="fa fa-plus fa-lg my-btn"></i>&nbsp&nbsp<label class="my-btn">Create Rule</label></td>
</tr>
</table>

<table id="rules-table" class="display responsive no-wrap">
  <thead>
    <tr>
      <th>Rule Id</th>
      <th>Rule name</th>
	<th>Destroy</th>
     </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td data-link="<%= edit_rule_path(rule) %>", style="cursor:pointer" ><%= rule.rule_id %></td>
        <td data-link="<%= edit_rule_path(rule) %>", style="cursor:pointer" ><%= rule.rule_name %></td>
        <!--<td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>-->
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table align="center"><tr align="right">
  <div class="field">
    <td align="right"><h4><%= f.label :rule_id %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :rule_id, size: "70x10", class: "form-control input-lg", placeholder: "" %></td>
  </div>
</tr>
  <tr><td><br></td></tr>
<tr align="right">
  <div class="field">
   <td align="right"><h4> <%= f.label :rule_name %></h4></td>
    <td align="right" style="padding-left:30px"><%= f.text_field :rule_name, size: "70x10", class: "form-control input-lg", placeholder: "Enter Rule Name" %></td>
  </div>
</tr>
</table>
<tr><td><br></td></tr>
<tr align="center">
  <div class="actions" align="center">
    <input class="btn btn-inverser my-btn" type="submit" value="Create Rule"></input>
  </div>
</tr>

<% end %>
<ul class="pager">

<li><%= link_to 'Back', rules_path %></li>
</ul>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rule:</strong>
  <%= @rule.rule_id %>
</p>

<p>
  <strong>Rule name:</strong>
  <%= @rule.rule_name %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>